Modify ocpv-demo for Ansible validated content
ansible-middleware/ocpv_lab pull request #2
Opened 2023-06-12 07:14 UTC by RanabirChakraborty

Issue: https://github.com/ansible-middleware/ocpv-demo/issues/1

2023-07-10 07:11 UTC, RanabirChakraborty commented
@sabre1041 can you please review this?
I'm unsure about the role description so I left it blank, Let me know what to fill up. 
We need to change the repo name to `ocpv-lab`; I have renamed it accordingly.
We also need to release `ocpv-lab` to create a `changelog`.

2023-07-12 15:22 UTC, sabre1041 requested changes

2023-07-12 15:22 UTC, sabre1041 commented on README.md
> +# Ansible Middleware OpenShift Virtualization lab
```suggestion
# Ansible Middleware OpenShift Virtualization Lab
```

2023-07-12 15:22 UTC, sabre1041 commented on README.md
> +Using of OpenShift Virtualization as an environment for hosting Virtual Machines that are provisioned, configured and maintained using Ansible and tooling from the Ansible Middleware project.
```suggestion
Using OpenShift Virtualization as an environment for hosting Virtual Machines that are provisioned, configured and maintained using Ansible and tooling from the Ansible Middleware project.
```

2023-07-12 15:22 UTC, sabre1041 commented on roles/configure-aap/README.md
> +[GPL2](https://github.com/ansible-middleware/ocpv-lab/blob/validated_content/LICENSE)
Can we change the license to Apache 2?

2023-07-12 15:22 UTC, sabre1041 commented on roles/ocpv-install/README.md
> +[GPL2](https://github.com/ansible-middleware/ocpv-lab/blob/validated_content/LICENSE)
Change to Apache 2

2023-07-18 16:27 UTC, RanabirChakraborty commented
@sabre1041 the changes are done. Can you please review once.

2023-07-18 17:47 UTC, sabre1041 requested changes

2023-07-18 17:47 UTC, sabre1041 commented on roles/configure-aap/README.md
> +[Apache License Version 2.0](https://github.com/ansible-middleware/ocpv-lab/blob/validated_content/LICENSE)
```suggestion
[Apache License Version 2.0](https://github.com/ansible-middleware/ocpv-lab/blob/main/LICENSE)
```

2023-07-19 11:58 UTC, sabre1041 approved these changes
LGTM

2023-07-19 11:58 UTC, merged