Fixing CI issues
ansible-middleware/ocpv_lab pull request #3
Opened 2023-07-20 14:46 UTC by RanabirChakraborty

Issue: https://github.com/ansible-middleware/ocpv-lab/issues/1

2023-07-20 14:47 UTC, RanabirChakraborty commented
@sabre1041 This should fix the CI issue now. There are still some wearing, let me know if we need to fix that as well.

2023-07-21 00:20 UTC, sabre1041 requested changes
Lets go ahead with the changes to fix the warnings so that we have clean set of assets

2023-07-21 00:20 UTC, sabre1041 commented on .github/workflows/ci.yml
>      name: molecule
Let's change the name since there is no Molecule being performed. If we want to add it later on, we can always rename the job back

2023-07-21 00:20 UTC, sabre1041 commented on galaxy.yml
> +name: ocpv-lab
We probably need to change the collection name to `ocpv_lab` including changing the name of the repository (again)

2023-07-21 00:20 UTC, sabre1041 commented on galaxy.yml
> +  - openShift
Lets keep all letters lowercased

2023-07-21 19:19 UTC, sabre1041 approved these changes
LGTM

2023-07-21 19:19 UTC, merged